# Generated by Django 3.1.4 on 2020-12-09 09:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customadmin', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='testimonial',
            old_name='designition',
            new_name='designation',
        ),
    ]
