# Generated by Django 3.1.4 on 2020-12-09 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customadmin', '0004_auto_20201209_1008'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShopProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True, verbose_name='Active')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Date when created.', null=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date when updated.', null=True, verbose_name='Updated At')),
                ('product_image', models.ImageField(blank=True, null=True, upload_to='products', verbose_name='Product images')),
                ('name', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('price', models.TextField(blank=True, default='', max_length=500, null=True)),
                ('detail', models.CharField(blank=True, default='', max_length=255, null=True)),
            ],
            options={
                'verbose_name': 'Shop Product',
                'verbose_name_plural': 'Shop Products',
                'ordering': ['-created_at'],
            },
        ),
    ]
