# Generated by Django 3.1.4 on 2020-12-10 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customadmin', '0007_service_servicecategory'),
    ]

    operations = [
        migrations.CreateModel(
            name='PhoneNumberCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True, verbose_name='Active')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Date when created.', null=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date when updated.', null=True, verbose_name='Updated At')),
                ('code', models.CharField(blank=True, max_length=200, null=True, unique=True)),
                ('code_text', models.TextField(blank=True, default='', max_length=255, null=True)),
            ],
            options={
                'verbose_name': 'Phone Number Code',
                'verbose_name_plural': 'Phone Number Codes',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserPhoneNumber',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True, verbose_name='Active')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Date when created.', null=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date when updated.', null=True, verbose_name='Updated At')),
                ('phone', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'verbose_name': 'User Phone Numer',
                'verbose_name_plural': 'User Phone Numers',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterField(
            model_name='service',
            name='price',
            field=models.FloatField(blank=True, default=50, null=True),
        ),
    ]
