# Generated by Django 3.1.4 on 2020-12-14 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customadmin', '0009_auto_20201211_0607'),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonalChart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True, verbose_name='Active')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Date when created.', null=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date when updated.', null=True, verbose_name='Updated At')),
                ('name', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('date_of_birth', models.DateField(blank=True, default='', null=True)),
            ],
            options={
                'verbose_name': 'Personal chart Detail',
                'verbose_name_plural': 'Personal chart Detail',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='user',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
    ]
