# Generated by Django 3.1.4 on 2020-12-17 11:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customadmin', '0012_purchasedproducts_timeslots_transactiondetail'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PurchasedProducts',
            new_name='PurchasedProduct',
        ),
    ]
