# Generated by Django 3.1.4 on 2020-12-17 11:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customadmin', '0013_auto_20201217_1131'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TimeSlots',
            new_name='TimeSlot',
        ),
    ]
