# Generated by Django 3.1.4 on 2020-12-18 10:22

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('customadmin', '0015_bookedservice'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bookedservice',
            options={'ordering': ['-created_at'], 'verbose_name': 'Booked Service', 'verbose_name_plural': 'Booked Services'},
        ),
        migrations.AddField(
            model_name='transactiondetail',
            name='active',
            field=models.BooleanField(default=True, verbose_name='Active'),
        ),
        migrations.AddField(
            model_name='transactiondetail',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='Date when created.', null=True, verbose_name='Created At'),
        ),
        migrations.AddField(
            model_name='transactiondetail',
            name='transaction_id',
            field=models.UUIDField(blank=True, default=uuid.uuid4, null=True),
        ),
        migrations.AddField(
            model_name='transactiondetail',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='Date when updated.', null=True, verbose_name='Updated At'),
        ),
    ]
