# Generated by Django 3.1.4 on 2020-12-21 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customadmin', '0017_auto_20201221_0553'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='otp_expired_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
