# Generated by Django 3.1.4 on 2020-12-22 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customadmin', '0019_auto_20201221_0614'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inquiry',
            name='note',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='inquiry',
            name='phone',
            field=models.CharField(blank=True, default='', max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='profile_image',
            field=models.ImageField(blank=True, default='profile_image/default-profile-image.jpg', null=True, upload_to='profile_image', verbose_name='Profile Image'),
        ),
    ]
