# Generated by Django 3.1.4 on 2020-12-29 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customadmin', '0023_user_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='FamilyCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True, verbose_name='Active')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Date when created.', null=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date when updated.', null=True, verbose_name='Updated At')),
                ('code', models.CharField(blank=True, max_length=3, null=True)),
                ('meaning', models.TextField(blank=True, default='', max_length=255, null=True)),
            ],
            options={
                'verbose_name': 'Family Code',
                'verbose_name_plural': 'Family Codes',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FoundationCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True, verbose_name='Active')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Date when created.', null=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date when updated.', null=True, verbose_name='Updated At')),
                ('code', models.CharField(blank=True, max_length=3, null=True)),
                ('meaning', models.TextField(blank=True, default='', max_length=255, null=True)),
            ],
            options={
                'verbose_name': 'Foundation Code',
                'verbose_name_plural': 'Foundation Codes',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='NumberCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True, verbose_name='Active')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Date when created.', null=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date when updated.', null=True, verbose_name='Updated At')),
                ('code', models.CharField(blank=True, max_length=1, null=True)),
                ('meaning', models.TextField(blank=True, default='', max_length=255, null=True)),
            ],
            options={
                'verbose_name': 'Number Code',
                'verbose_name_plural': 'Number Codes',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OtherCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True, verbose_name='Active')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Date when created.', null=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date when updated.', null=True, verbose_name='Updated At')),
                ('code', models.CharField(blank=True, max_length=3, null=True)),
                ('meaning', models.TextField(blank=True, default='', max_length=255, null=True)),
            ],
            options={
                'verbose_name': 'Other Code',
                'verbose_name_plural': 'Other Codes',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SocialCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True, verbose_name='Active')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Date when created.', null=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date when updated.', null=True, verbose_name='Updated At')),
                ('code', models.CharField(blank=True, max_length=3, null=True)),
                ('meaning', models.TextField(blank=True, default='', max_length=255, null=True)),
            ],
            options={
                'verbose_name': 'Social Code',
                'verbose_name_plural': 'Social Codes',
                'ordering': ['-created_at'],
            },
        ),
    ]
