# Generated by Django 3.1.4 on 2021-01-28 12:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customadmin', '0025_auto_20201230_0543'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='related_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='related_service', to='customadmin.service'),
        ),
    ]
