# Generated by Django 3.1.4 on 2021-03-04 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customadmin', '0029_user_device'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phonenumbercode',
            name='code_text',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
