# Generated by Django 3.1.4 on 2021-03-19 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customadmin', '0030_auto_20210304_0830'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicecategory',
            name='category_description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
