# Generated by Django 3.1.4 on 2021-03-23 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customadmin', '0032_categoryimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicecart',
            name='service_type',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
