# Generated by Django 3.1.4 on 2021-03-24 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customadmin', '0034_bookedservice_service_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicecart',
            name='service_type',
            field=models.CharField(blank=True, choices=[('Local', 'Local'), ('Overseas', 'Overseas')], default='', max_length=100, null=True),
        ),
    ]
